name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  COMPANY: nedra-digital
  AUTHORS: karinskiy.andrey@gmail.com
  PRODUCT: PROJECT
  DOTNET: 6.0.x
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      src: ./source

    steps:
      - uses: actions/checkout@v3
    
      - name: Run read-yaml action
        id: package-metadata
        uses: KJ002/read-yaml@main
        with:
          file: './././component.yml'
          key-path: '["component"]'

      - name: Display read-yaml output
        run: echo "${{ steps.package-metadata.outputs.data.product }}"
        
      - name: Replace placeholders with environment variables
        uses: cschleiden/replace-tokens@v1.1
        with:
          tokenPrefix: '{{'
          tokenSuffix: '}}'
          files: '["**/*.md", "**/*.props"]'
        env:
          REPOSITORY: https://github.com/${{env.COMPANY}}/${{github.event.repository.name}} 
          
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        
      - name: Enable SemVer 
        uses: dotnet/nbgv@master
        id: nbgv
        
      - name: Show current version
        run:  
          echo ${{steps.nbgv.outputs.SemVer2}} 
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{env.DOTNET}}
          source-url: https://nuget.pkg.github.com/${{env.COMPANY}}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}     
